/*

Week 8
Sounds / MIDI Song

*/

document.title = "W8 - Sounds / MIDI Song";

const SHARED_PATH = "../../../shared/";
const COLORS = GLOBALS.colors;

// prettier-ignore
const MARY_HAD_A_LITTLE_LAMB = [ 64, 62, 60, 62,  64, 64, 64, null,   62, 62, 62, null,   64 , 64, 64, null, 64, 62, 60, 62,  64, 64, 64, 64,   62, 62, 64, 62,   60 , null, null, null];

// midiToFreq isn't in p5.js 2.0
// generated by Gemini Fast 3
function midiToFreq(midiNote) {
  return 440 * Math.pow(2, (midiNote - 69) / 12); // 69: A4 midi number
}

class MidiMusic {
  constructor() {
    this.currentNoteIndex = 0;
    this.musicNotes = MARY_HAD_A_LITTLE_LAMB;
  }

  /** @returns {number | null} The next note's midi number or null for a rest */
  getNextNote() {
    const midiNote = this.musicNotes[this.currentNoteIndex];
    this.currentNoteIndex++;
    if (this.currentNoteIndex === this.musicNotes.length)
      this.currentNoteIndex = 0;
    return midiNote;
  }
}

class MidiPlayer {
  notesPlayed = 0; // used to determine whether to cancel a fade out

  constructor(/** @type {p5.TriOsc} */ osc) {
    this.osc = osc;
    osc.amp(0);
    osc.start();
  }

  playNote(/** @type {number | null} */ midiNumber, durationMs = 300) {
    // with start/stop instead of amping down
    // if (midiNumber === null) {
    //   this.osc.stop();
    // } else {
    //   this.osc.freq(midiToFreq(midiNumber));
    //   this.osc.amp(0.1);
    //   this.osc.start();
    // }

    if (midiNumber !== null) {
      this.notesPlayed++;
      const currentNotePlayedCount = this.notesPlayed;

      this.osc.freq(midiToFreq(midiNumber));
      this.osc.amp(0.2, 0.05);

      setTimeout(() => {
        // don't amp down if another note is already playing
        if (this.notesPlayed > currentNotePlayedCount) return;
        this.osc.amp(0, 0.1);
      }, durationMs);
    }
  }
}

class VisualKeyboard {
  constructor(/** @type {string[]} */ keys) {
    this.keys = keys;
    this.nKeys = Object.keys(keys).length;
    this.resetPressedKeys();
  }

  resetPressedKeys() {
    this.pressedKeys = {};
    for (const k of this.keys) {
      this.pressedKeys[k] = false;
    }
  }

  setPressedKeys(/** @type {Record<string, boolean>} */ pressedKeys) {
    this.pressedKeys = { ...this.pressedKeys, ...pressedKeys };
  }

  draw(x, y, width, height) {
    push();
    translate(x, y);
    const keyWidth = width / this.nKeys;

    let i = 0;
    for (const [k, isPressed] of Object.entries(this.pressedKeys)) {
      if (isPressed) fill(90);
      else fill(255);

      const x = i * keyWidth;
      rect(x, 0, keyWidth, height);
      textSize(keyWidth * 0.2);
      textAlign(LEFT, TOP);
      fill(0);
      text(k, x, 0);
      i++;
    }

    pop();
  }
}

/** @type {MidiPlayer} */
let midiPlayer;
const midiNotes = new MidiMusic();
/** @type {VisualKeyboard} */
let visualKeyboard;
let audioStarted = false;

async function setup() {
  getAudioContext().suspend();
  createCanvas(windowWidth, windowHeight);
  frameRate(60);

  midiPlayer = new MidiPlayer(new p5.TriOsc());
  visualKeyboard = new VisualKeyboard(["60", "62", "64"]);
}

function draw() {
  const TEXT_SIZE = min(width, height) * 0.05;

  if (!audioStarted) {
    background(220);
    textSize(TEXT_SIZE);
    textAlign(CENTER, CENTER);
    text("Click to begin!", width / 2, height / 2);
    return;
  }

  if (frameCount % 30 === 0) {
    background(220);
    const note = midiNotes.getNextNote();
    midiPlayer.playNote(note);

    textSize(TEXT_SIZE);
    textAlign(CENTER, TOP);
    text(note ? note : "[rest]", width / 2, 0);

    visualKeyboard.resetPressedKeys();
    if (note) visualKeyboard.setPressedKeys({ ["" + note]: true });
  }

  const keyboardDims = { w: width / 2, h: height / 2 };
  visualKeyboard.draw(
    width / 2 - keyboardDims.w / 2,
    height / 2 - keyboardDims.h / 2,
    keyboardDims.w,
    keyboardDims.h,
  );
}

function mousePressed() {
  if (!audioStarted) {
    audioStarted = true;
    userStartAudio();
  }
}

function windowResized() {
  resizeCanvas(windowWidth, windowHeight);
}
